### ISSUE TITLE
Invalid template in some of the commands to create new Farm projects on the Quick Start page

### ISSUE THREAD

**Issue by joaopalmeiro** [farm-fe/docs#103]
Hi! 👋 

When trying to create a new Farm project from one of the [npm commands](https://www.farmfe.org/docs/quick-start#create-a-farm-project) (`npm 7+`) available on the [Quick Start page](https://www.farmfe.org/docs/quick-start) of the documentation, I got this error:

```plain
npm create farm@latest my-vue-app -- --template vue

 ⚡ Welcome To Farm !



 error: failed to parse 'vue': vue is not a valid template. Valid templates are [vanilla, react, vue3, vue2, lit, svelte, solid, preact, nestjs, tauri, tauri-React - (https://react.dev/), tauri-Vue3 - (https://vuejs.org/), tauri-Vanilla, tauri-Svelte - (https://svelte.dev/), tauri-Solid - (https://solidjs.com/), tauri-Preact - (https://preactjs.com/), electron, electron-React - (https://react.dev/), electron-Vue3 - (https://vuejs.org/), electron-Vanilla, electron-Svelte - (https://svelte.dev/), electron-Solid - (https://solidjs.com/), electron-Preact - (https://preactjs.com/)]

npm ERR! code 1
npm ERR! path /Users/joao.palmeiro/Documents
npm ERR! command failed
npm ERR! command sh -c create-farm my-vue-app --template vue

npm ERR! A complete log of this run can be found in: /Users/joao.palmeiro/.npm/_logs/2024-06-22T08_02_31_878Z-debug-0.log
```

I think it's because the `vue` template doesn't exist (the [Vue-related templates](https://github.com/farm-fe/farm/blob/v1.2.0/crates/create-farm-rs/src/template.rs#L160) are the `vue3` and `vue2` templates). Furthermore, these commands are not consistent with each other as Yarn's, for example, uses the `react` template. So, I think it would be useful to standardize the template chosen in these commands for `react` or `vue3` (and the project folder name if necessary).

Let me know your thoughts and if I can open a PR!

Thanks! 😄

**Comment by ErKeLost** [comment]
Thanks, maybe we need to modify the document and use the react module version by default welcome pr，If you want, you can change it directly on the new_doc branch

**Comment by joaopalmeiro** [comment]
Hi, @ErKeLost!

I was checking the `feat/new_doc` branch and this issue no longer seems to be a problem on the [Quick Start page](https://github.com/farm-fe/docs/blob/feat/new_doc/docs/quick-start.mdx?plain=1), as the template used is already `react`. However, the issue persists for the [zh version](https://github.com/farm-fe/docs/blob/feat/new_doc/i18n/zh/docusaurus-plugin-content-docs/current/quick-start.mdx) if I'm getting it right. 

What should I do? Update the [current version](https://github.com/farm-fe/docs/blob/1b30378deb605081cd4cc7111f6a5e95c290e334/docs/quick-start.mdx) in the `main` branch, update the [zh version](https://github.com/farm-fe/docs/blob/feat/new_doc/i18n/zh/docusaurus-plugin-content-docs/current/quick-start.mdx) in the `feat/new_doc` branch, or something different?

Thanks!

**Comment by ErKeLost** [comment]
The branch on `new_doc` branch will be online soon, so modifications to the documentation can be made on `new_doc`. It may be that I have modified it before. Everything is based on the `new_doc` branch. Sorry for neglecting this. We will launch new documentation in the next few days. , before that, there are still many things that need to be done. If you are willing, you can modify it on the main branch first and I will merge it. Thank you. Or do you want to contribute other parts of the document? Thanks again

**Comment by joaopalmeiro** [comment]
Thanks for the clarification! 

I'll open a PR for the `main` branch since the command doesn't work as is, and it's currently the online version, if that's ok.

I haven't identified anything else for now (I'm still experimenting with Farm), but if I find anything extra, I'll first check if it's still an issue in the `feat/new_doc` branch and open an issue if necessary to propose changes there.
